name       : eigen2
version    : 2.0.17
release    : 6
source     :
    - https://bitbucket.org/eigen/eigen/get/2.0.17.tar.bz2 : 7255e856ed367ce6e6e2d4153b0e4e753c8b8d36918bf440dd34ad56aff09960
license    : LGPL-3.0
component  : programming
summary    : Eigen is a C++ template library for linear algebra.
description: |
    Eigen is a C++ template library for linear algebra.
patterns   :
    - /usr/include/eigen2
    - /usr/share
replaces   :
    - eigen2-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
